kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4 #version of kind config
name: clusterspringbootapis # name of your cluster match `^[a-z0-9.-]+$`
networking:
    ipFamily: ipv4
    apiServerAddress: 127.0.0.1
nodes:
    - role: control-plane #multi-node cluster
    - role: worker
    - role: worker
featureGates:
    # any feature gate can be enabled here with "Name": true
    # or disabled here with "Name": false
    # not all feature gates are tested, however
    "CSIMigration": true
