apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql8 # como o deployment se chamará
    labels:
        app: mysql8 # como nosso deployment será referenciado nos services e outros blocos
spec:
    replicas: 1
    selector:
        matchLabels: # como os outro serviços irão chamá-lo
            app: mysql8
    template:
        metadata:
            labels:
                app: mysql8 # a quem nosso template se aplica
        spec:
            containers:
                - name: mysql8
                  image: mysql:8
                  resources:
                      limits:
                          memory: "500Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 3306
                  env:
                      - name: MYSQL_DATABASE
                        value: vollmed_api
                      - name: MYSQL_USER
                        value: user
                      - name: MYSQL_PASSWORD
                        value: pass
                      - name: MYSQL_ROOT_PASSWORD
                        value: pass
